name: Compile and Sign Kodi for Android TV (32-bit and 64-bit)

on:
  push:
    branches: [ Matrix ]
  pull_request:
    branches: [ Matrix ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm, arm64]

    steps:
    - uses: actions/checkout@v2
      with:
        repository: xbmc/xbmc
        ref: Matrix
        submodules: recursive

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential default-jdk python3-pip autoconf libtool automake unzip zip
        pip3 install --user cmake

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Install Android NDK
      run: |
        sdkmanager --install "ndk;22.0.7026061"
        echo "ANDROID_NDK=$ANDROID_HOME/ndk/22.0.7026061" >> $GITHUB_ENV

    - name: Configure build
      run: |
        mkdir -p build && cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
              -DANDROID_ABI=${{ matrix.arch == 'arm' && 'armeabi-v7a' || 'arm64-v8a' }} \
              -DANDROID_PLATFORM=android-21 \
              -DCMAKE_BUILD_TYPE=Release \
              -DCORE_PLATFORM_NAME=android \
              -DANDROID_NDK=$ANDROID_NDK \
              ..
    
    - name: Build Kodi
      run: |
        cd build
        make -j$(nproc)

    - name: Package APK
      run: |
        cd build
        make apk

    - name: Generate signing key
      run: |
        keytool -genkey -v -keystore my-release-key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias my-alias -storepass ${{ secrets.KEYSTORE_PASSWORD }} -keypass ${{ secrets.KEY_PASSWORD }} -dname "CN=YourName, OU=YourOrganizationalUnit, O=YourOrganization, L=YourCity, S=YourState, C=YourCountry"

    - name: Sign APK
      run: |
        jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore my-release-key.jks -storepass ${{ secrets.KEYSTORE_PASSWORD }} -keypass ${{ secrets.KEY_PASSWORD }} build/${{ matrix.arch }}/kodi-*.apk my-alias

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: kodi-android-tv-${{ matrix.arch }}
        path: build/${{ matrix.arch }}/kodi-*.apk
